In [2]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
runs = np.array(df['Runs'])
print(runs[0])

5611


In [3]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
runs_3P = np.array(df['Runs'])
print(runs[2])

3200


In [4]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
last_player_run = np.array(df['Runs'])
print(last_player_run[-1])

3250


In [10]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df[['Runs', 'Wickets']])
print(arr[0])

[5611   15]


In [12]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
print(arr[1])

12


In [15]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
print(arr[0:5])

[5611   12 3200 4978 2386]


In [18]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
print(arr[-5:])

[  85   52 4965 1522 3250]


In [19]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
print(arr[3:10])

[4978 2386 6624 5162 1852  968 2838]


In [20]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
print(arr[::2])

[5611 3200 2386 5162  968 2582 3890 5254   52 1522]


In [21]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
print(arr[::-1])

[3250 1522 4965   52   85 5254 1534 3890  420 2582 2838  968 1852 5162
 6624 2386 4978 3200   12 5611]


In [24]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df[['Runs', 'PlayerName', 'Team']])
print(arr[0:3])

[[5611 'Rohit Sharma' 'Mumbai Indians']
 [12 'Jasprit Bumrah' 'Mumbai Indians']
 [3200 'Suryakumar Yadav' 'Mumbai Indians']]


In [25]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
print(arr.dtype)

int64


In [26]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'], dtype='float')
print(arr)

[5611.   12. 3200. 4978. 2386. 6624. 5162. 1852.  968. 2838. 2582.  420.
 3890. 1534. 5254.   85.   52. 4965. 1522. 3250.]


In [27]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
newarr = arr.copy()
arr[0] = 100
print(arr)
print(newarr)

[ 100   12 3200 4978 2386 6624 5162 1852  968 2838 2582  420 3890 1534
 5254   85   52 4965 1522 3250]
[5611   12 3200 4978 2386 6624 5162 1852  968 2838 2582  420 3890 1534
 5254   85   52 4965 1522 3250]


In [28]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
newarr = arr.view()
arr[0] = 999
print(arr)
print(newarr)

[ 999   12 3200 4978 2386 6624 5162 1852  968 2838 2582  420 3890 1534
 5254   85   52 4965 1522 3250]
[ 999   12 3200 4978 2386 6624 5162 1852  968 2838 2582  420 3890 1534
 5254   85   52 4965 1522 3250]


In [29]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)


None
[5611   12 3200 4978 2386 6624 5162 1852  968 2838 2582  420 3890 1534
 5254   85   52 4965 1522 3250]


In [30]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
print(arr.shape)

(20,)


In [31]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
newarr = arr.reshape(4, 5)
print(newarr)

[[5611   12 3200 4978 2386]
 [6624 5162 1852  968 2838]
 [2582  420 3890 1534 5254]
 [  85   52 4965 1522 3250]]


In [32]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
newarr = arr.reshape(2, 10)
print(newarr)

[[5611   12 3200 4978 2386 6624 5162 1852  968 2838]
 [2582  420 3890 1534 5254   85   52 4965 1522 3250]]


In [33]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
print(arr.ndim)

1


In [34]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
print(arr.size)

20


In [35]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
for i in runs:
  print(i)

5611
12
3200
4978
2386
6624
5162
1852
968
2838
2582
420
3890
1534
5254
85
52
4965
1522
3250


In [41]:
from numpy._core.multiarray import nditer
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df[['Runs', 'Catches']])
for i in np.nditer(arr):
  print(i)

5611
12
3200
4978
2386
6624
5162
1852
968
2838
2582
420
3890
1534
5254
85
52
4965
1522
3250
72
25
45
150
65
95
72
38
52
68
42
28
55
35
62
18
32
55
28
72


In [45]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
for i, arr in np.ndenumerate(arr):
  print(i, arr)

(0,) 5611
(1,) 12
(2,) 3200
(3,) 4978
(4,) 2386
(5,) 6624
(6,) 5162
(7,) 1852
(8,) 968
(9,) 2838
(10,) 2582
(11,) 420
(12,) 3890
(13,) 1534
(14,) 5254
(15,) 85
(16,) 52
(17,) 4965
(18,) 1522
(19,) 3250


In [51]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df[['Runs', 'Wickets']])
newarr = np.concatenate([['Runs', 'Wickets']])
print(newarr, arr)

['Runs' 'Wickets'] [[5611   15]
 [  12  145]
 [3200    8]
 [4978    0]
 [2386  110]
 [6624    4]
 [5162    0]
 [1852   85]
 [ 968  127]
 [2838    0]
 [2582    0]
 [ 420  112]
 [3890    0]
 [1534   22]
 [5254    2]
 [  85   78]
 [  52  142]
 [4965   18]
 [1522    0]
 [3250    0]]


In [54]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df[['Runs', 'Wickets']])
newarr = np.vstack([['Runs', 'Wickets']])
print(newarr, arr)

[['Runs' 'Wickets']] [[5611   15]
 [  12  145]
 [3200    8]
 [4978    0]
 [2386  110]
 [6624    4]
 [5162    0]
 [1852   85]
 [ 968  127]
 [2838    0]
 [2582    0]
 [ 420  112]
 [3890    0]
 [1534   22]
 [5254    2]
 [  85   78]
 [  52  142]
 [4965   18]
 [1522    0]
 [3250    0]]


In [55]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df[['Runs', 'Wickets']])
newarr = np.hstack([['Runs', 'Wickets']])
print(newarr, arr)

['Runs' 'Wickets'] [[5611   15]
 [  12  145]
 [3200    8]
 [4978    0]
 [2386  110]
 [6624    4]
 [5162    0]
 [1852   85]
 [ 968  127]
 [2838    0]
 [2582    0]
 [ 420  112]
 [3890    0]
 [1534   22]
 [5254    2]
 [  85   78]
 [  52  142]
 [4965   18]
 [1522    0]
 [3250    0]]


In [57]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df[['Runs', 'Wickets', 'Catches']])
newarr = np.concatenate([['Runs', 'Wickets', 'Catches']])
print(newarr, arr)

['Runs' 'Wickets' 'Catches'] [[5611   15   72]
 [  12  145   25]
 [3200    8   45]
 [4978    0  150]
 [2386  110   65]
 [6624    4   95]
 [5162    0   72]
 [1852   85   38]
 [ 968  127   52]
 [2838    0   68]
 [2582    0   42]
 [ 420  112   28]
 [3890    0   55]
 [1534   22   35]
 [5254    2   62]
 [  85   78   18]
 [  52  142   32]
 [4965   18   55]
 [1522    0   28]
 [3250    0   72]]


In [60]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
newarr = np.array_split(arr, 4)
print(newarr)

[array([5611,   12, 3200, 4978, 2386]), array([6624, 5162, 1852,  968, 2838]), array([2582,  420, 3890, 1534, 5254]), array([  85,   52, 4965, 1522, 3250])]


In [61]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
newarr = np.array_split(arr, 2)
print(newarr)

[array([5611,   12, 3200, 4978, 2386, 6624, 5162, 1852,  968, 2838]), array([2582,  420, 3890, 1534, 5254,   85,   52, 4965, 1522, 3250])]


In [63]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
newarr = np.sort(arr)
print(newarr)

[  12   52   85  420  968 1522 1534 1852 2386 2582 2838 3200 3250 3890
 4965 4978 5162 5254 5611 6624]


In [64]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
newarr = (np.sort(arr) [::-1])
print(newarr)

[6624 5611 5254 5162 4978 4965 3890 3250 3200 2838 2582 2386 1852 1534
 1522  968  420   85   52   12]


In [65]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
newarr = np.where(arr > 5000)
print(newarr)

(array([ 0,  5,  6, 14]),)


In [66]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
print(arr > 1000)

[ True False  True  True  True  True  True  True False  True  True False
  True  True  True False False  True  True  True]


In [67]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Runs'])
print(arr < 1000)

[False  True False False False False False False  True False False  True
 False False False  True  True False False False]


In [69]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Salary_Crore'])
print(arr > 12)

[ True False False False  True  True False False False  True False  True
 False False False False False False  True  True]


In [70]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Wickets'])
print(arr > 100)

[False  True False False  True False False False  True False False  True
 False False False False  True False False False]


In [71]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Economy'])
print(arr < 7)

[False  True False  True False False  True False  True  True  True  True
  True False False False False False  True  True]


In [72]:
import numpy as np
import pandas as pd
df = pd.read_csv('IPL_NUMPY.csv')
arr = np.array(df['Catches'])
print(arr > 50)

[ True False False  True  True  True  True False  True  True False False
  True False  True False False  True False  True]
